name: Run Python script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Install dependencies
        run: pip install scikit-learn

      - name: Install jsonify
        run: pip install jsonify

      - name: Install dependencies
        run: pip install flask

      - name: Install dependencies
        run: pip install numpy

      - name: Install dependencies
        run: pip install pickle

      - name: Run Python script
        run: python main.py
